# Generated by Django 4.2.6 on 2023-10-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='actuality',
            field=models.CharField(choices=[('Actual', 'Actual'), ('Not actual', 'Not actual')], default=('Actual', 'Actual'), max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
